distributable:
  url: https://mirrors.edge.kernel.org/pub/software/scm/git/git-{{version}}.tar.xz
  strip-components: 1

versions:
  github: git/git/tags

dependencies:
  zlib.net: 1
  gnu.org/gettext: ^0.21
  curl.se: '>=5'
  perl.org: '*'

build:
  dependencies:
    tea.xyz/gx/cc: c99
    tea.xyz/gx/make: '*'
  script: |
    mv props/config.mak .

    ./configure $CONF
    make install $BAKE

    cd "{{prefix}}"
    DEBUG=1 fix-shebangs.ts bin/* libexec/git-core/*
  env:
    V: 1
    BAKE:
    - --jobs {{ hw.concurrency }}
    - NO_TCLTK=1
    CONF:
    - --prefix={{ prefix }}
    - --with-perl={{ deps.perl.org.prefix }}
    INSTALL_STRIP: -s

test: |
  git clone https://github.com/teaxyz/white-paper
