name: tea/pantry/stage-build-artifacts
description: internal tea.xyz specific at this time

inputs:
  platform:
    description: ''
    required: true
  AWS_S3_BUCKET:
    description: ''
    required: true
  AWS_ACCESS_KEY_ID:
    description: ''
    required: true
  AWS_SECRET_ACCESS_KEY:
    description: ''
    required: true

runs:
  using: composite
  steps:
    - uses: teaxyz/pantry.core/.github/actions/cache@cache-brewkit

    - uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.platform }}

    - run: scripts/cache-artifacts.ts
        ${{github.repository}}
        ${{github.ref}}
        ${{inputs.platform}}
        artifacts.tgz
      env:
        AWS_S3_CACHE: ${{ inputs.AWS_S3_CACHE }}
        AWS_ACCESS_KEY_ID: ${{ inputs.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
