distributable:
  url: https://github.com/teaxyz/brewkit/archive/refs/tags/v{{ version }}.tar.gz
  strip-components: 1

versions:
   github: teaxyz/brewkit

dependencies:
  deno.land: ^1.30
  gnu.org/bash: '*'
  tea.xyz: ^0

build:
  mv bin libexec share deno.* {{prefix}}

test:
  test zlib.net
  # we would like to test builds but we need a `GITHUB_TOKEN` and
  # currently that is not possible
