distributable:
  url: https://github.com/teaxyz/brewkit/archive/refs/tags/v{{ version }}.tar.gz
  strip-components: 1

versions:
   github: teaxyz/brewkit

dependencies:
  deno.land: ^1.30
  gnu.org/bash: '*'
  tea.xyz: ^0

build: |
  mkdir -p {{prefix}}
  rm -rf {{prefix}}/*  # because our build infra uses this pkg to build itself
  mv bin libexec share deno.* {{prefix}}

test:
  dependencies:
    zlib.net: '*'
  script:
    test zlib.net
    # we would like to test builds but we need a `GITHUB_TOKEN` and
    # (currently) we can’t figure out how to set that up in CI/CD
