distributable:
  url: https://github.com/npm/cli/archive/refs/tags/v{{ version }}.tar.gz
  strip-components: 1

versions:
  github: npm/cli

provides:
  - bin/npm
  - bin/npx

dependencies:
  nodejs.org: '>=14'

build:
  script:
    node . install --global --prefix={{prefix}}

test:
  script: |
    npm -g doctor
    npx -q tldr ls