distributable:
  url: https://github.com/npm/cli/archive/refs/tags/v{{ version }}.tar.gz
  strip-components: 1

versions:
  github: npm/cli

provides:
  - bin/npm
  - bin/npx

dependencies:
  nodejs.org: '>=14'

build:
  script:
    node . install --global --prefix={{prefix}}

test:
  dependencies:
    git-scm.org: '*' # `npm doctor` checks for, but doesn't use, `git`
  script: |
    npm doctor
    npx -q tldr ls