name: +tea.xyz/brewkit
description: sets up tea, tea.xyz/brewkit & caching

# inputs and outputs are `teaxyz/setup` passthrough

inputs:
  prefix:
    description: >
      Where tea stows its packages.
      Defaults to `$HOME/.tea`.
    required: false
outputs:
  version:
    description: Your project’s version.
    value: ${{ steps.tea.outputs.version }}
  prefix:
    description: The prefix you specified.
    value: ${{ steps.tea.outputs.prefix }}

runs:
  using: composite
  steps:
    - run: |
        if [[ "$RUNNER_OS" == "macOS" ]]; then
          echo "cache=~/Library/Caches/deno" >> $GITHUB_OUTPUT
        else
          echo "cache=~/.cache/deno" >> $GITHUB_OUTPUT
        fi
      id: os-cache
      shell: sh

    - uses: teaxyz/setup@v0
      id: tea
      with:
        prefix: ${{ inputs.prefix }}
        +: tea.xyz/brewkit
        # prevent pantry from reassigning TEA_PREFIX etc.
        srcroot: null

    - run: |
        if test -d "{{ github.workspace }}"/projects; then
          echo "TEA_PANTRY_PATH=${{ github.workspace }}" >> $GITHUB_ENV
        fi
      shell: sh

    - uses: actions/cache@v3
      with:
        path: |
          ~/.deno
          ${{ steps.os-cache.outputs.cache }}
        key: ${{ runner.os }}-deno-${{ hashFiles(format('{0}/tea.xyz/brewkit/v\*/deno.jsonc', steps.tea.outputs.prefix)) }}
