distributable:
  url: https://github.com/westes/flex/releases/download/v2.6.4/flex-2.6.4.tar.gz
  strip-components: 1

versions:
  github: westes/flex
  strip: /^flex /

dependencies:
  gnu.org/m4: 1

build:
  dependencies:
    tea.xyz/gx/cc: c99
    tea.xyz/gx/make: '*'
  script: |
    ./configure --prefix={{ prefix }}
    make --jobs {{ hw.concurrency }} install
  env:
    darwin:
      MACOSX_DEPLOYMENT_TARGET: 10.6  #FIXME our default (11) breaks the build

test:
  dependencies:
    tea.xyz/gx/cc: c99
  script: |
    flex test.flex
    cc lex.yy.c -lfl
    OUT=$(echo "Hello World" | ./a.out)
    test "$OUT" = "Hello
    World"

provides:
  - bin/flex
  - bin/flex++
