distributable:
  url: https://ftp.gnu.org/gnu/readline/readline-{{ version.raw }}.tar.gz
  strip-components: 1

versions:
  #TODO brew has a couple patches we should apply
  - v8.1

dependencies:
  invisible-island.net/ncurses: 6

build:
  dependencies:
    tea.xyz/gx/cc: c99
    tea.xyz/gx/make: '*'
  script: |
    ./configure --prefix={{ prefix }} --with-curses
    make --jobs {{ hw.concurrency }} install

test:
  script: true  #FIXME
