distributable:
  url: https://nodejs.org/dist/v{{ version }}/node-v{{ version }}.tar.xz
  strip-components: 1

versions:
  github: nodejs/node/tags

companions:
  npmjs.com: '*'

dependencies:
  unicode.org: '>=71'
  openssl.org: 1.1
  zlib.net: 1

provides:
  - bin/node

interprets:
  extensions: js
  args: node

build:
  dependencies:
    tea.xyz/gx/cc: c99
    tea.xyz/gx/make: '*'
    python.org: '>=3.7 <3.11'
    freedesktop.org/pkg-config: ^0.29
  script: |
    ./configure $ARGS

    # FIXME: currently, dynamic builds of nodejs.org are segfaulting on linux/x86-64
    # if test "{{hw.platform}}/{{hw.arch}}" = "linux/x86-64"; then
    #   for i in out/tools/v8_gypfiles/gen-regexp-special-case.target.mk out/test_crypto_engine.target.mk; do
    #     if test -f "$i"; then
    #       sed -i.bak -e 's/\-static//g' $i
    #       rm $i.bak
    #     fi
    #   done
    # fi

    make --jobs {{ hw.concurrency }} install

    ls -l {{prefix}}/bin
    ldd {{prefix}}/bin/*
  env:
    ARGS:
    - --without-npm
    - --prefix={{ prefix }}
    # like, maybe we should include this?
    - --without-corepack
    - --with-intl=system-icu
    - --shared-openssl
    - --shared-zlib
    linux/x86-64:
      ARGS:
      - --fully-static
      - --enable-static

test:
  script: |
    out=$(node $FIXTURE)
    test "$out" = "Hello, world!"
  fixture:
    console.log("Hello, world!");
