distributable:
  url: https://github.com/teaxyz/cli/releases/download/v{{ version }}/tea-{{ version }}.tar.xz
  strip-components: 2
  #FIXME I have no idea why we must strip TWO components
  # when I manually extract the tarball it only has one but if we specify 1
  # both here and manually it has that same component *still*

versions:
  github: teaxyz/cli

provides:
  - bin/tea

build:
  dependencies:
    deno.land: '>=1.23 <1.25 || ^1.25.3'
    # ^^ 1.25.0 - 1.25.2 panics on Linux for us
  working-directory: ${{prefix}}/bin
  script:
    deno task --config "$SRCROOT"/deno.jsonc compile

test: |
  tea --version
  test "$(tea --version)" = "tea {{ version }}"
