distributable:
  url: https://github.com/mesonbuild/meson/releases/download/{{ version }}/meson-{{ version }}.tar.gz
  strip-components: 1

versions:
  github: mesonbuild/meson/tags

dependencies:
  python.org: 3
  gnu.org/bash: '>=2'  # for our venv/relocation scripts: feel free to fix that

build:
  python-venv.sh "{{prefix}}/bin/meson"

test:
  dependencies:
    ninja-build.org: 1
    tea.xyz/gx/cc: c99
  script: |
    meson ..
    test -f build.ninja
  working-directory: build

provides:
  - bin/meson