name: Cache Brewkit
description: sets up tea.xyz/brewkit with caching

inputs:
  platform:
    description: >
      The platform+arch to get specs for
    required: true
outputs:
  os:
    description: the OS for general tasks
    value: ${{ steps.platform.outputs.os }}
  build-os:
    description: the OS for build tasks
    value: ${{ steps.platform.outputs.build-os }}
  container:
    description: the container for build tasks
    value: ${{ steps.platform.outputs.container }}
  test-matrix:
    description: the matrix of os/containers for test tasks
    value: ${{ steps.platform.outputs.test-matrix }}

runs:
  using: composite
  steps:
    - uses: teaxyz/pantry.core/.github/actions/setup-brewkit@cache-brewkit
      with:
        cache-prefix: get-platform
    - run: ${{github.action_path}}/scripts/get-platform.ts
      shell: sh
      id: platform
      env:
        PLATFORM: ${{ inputs.platform }}
