distributable:
  url: https://github.com/rubygems/rubygems/archive/refs/tags/v{{version}}.tar.gz
  strip-components: 1

versions:
  github: rubygems/rubygems

dependencies:
  ruby-lang.org: '>=2.3'

build:
  script: |
    ruby setup.rb --prefix={{prefix}} --env-shebang

test:
  dependencies:
    tea.xyz/gx/cc: c99
    tea.xyz/gx/make: '*'
  script: |
    gem install awesome_print
    ruby -e 'require "rubygems"' -e 'require "awesome_print"' -e'ap $LOAD_PATH'
    gem install hexapdf
    hexapdf version

provides:
  - bin/bundle
  - bin/bundler
  - bin/gem
  - bin/rake
  - bin/rbs
  - bin/rdbg
  - bin/typeprof
