name: ci-scripts

on:
  pull_request:
    paths:
      - scripts/**.ts
      - import-map.json

jobs:
  typecheck:
    runs-on: ubuntu-latest
    env:
      TEA_SECRET: ${{ secrets.TEA_SECRET }}
    steps:
      - uses: actions/checkout@v3
      - uses: teaxyz/setup@v0
      - run: tea deno check --unstable --import-map=import-map.json scripts/*.ts
