name: ci-scripts

on:
  pull_request:
    paths:
      - scripts/**/*.ts

jobs:
  typecheck:
    runs-on: ubuntu-latest
    env:
      TEA_SECRET: ${{ secrets.TEA_SECRET }}
    steps:
      - uses: actions/checkout@v3
      - uses: teaxyz/setup@v0
      - run: deno check --unstable scripts/*.ts
