name: ci·scripts

on:
  pull_request:
    paths:
      - .github/**.ts

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: teaxyz/setup@v0
        with:
          srcroot: .github
      - uses: teaxyz/pantry.core/.github/actions/cache@cache-brewkit
      - run: deno check --unstable **/*.ts
        working-directory: .github
