name: ci
on: pull_request

jobs:
  get-diff:
    runs-on: ubuntu-latest
    outputs:
      diff: ${{ steps.diff.outputs.diff }}
    steps:
      - uses: actions/checkout@v3
      - uses: technote-space/get-diff-action@v6
        id: diff
        with:
          PATTERNS: projects/**/package.yml
  build:
    needs: [get-diff]
    uses: ./.github/workflows/build.yml
    with:
      projects: ${{ needs.get-diff.outputs.diff || 'zlib.net' }}
    secrets: inherit

  notify:
    if: always()
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: martialonline/workflow-status@v3
        id: status
      - uses: rtCamp/action-slack-notify@v2
        if: ${{ env.SLACK_WEBHOOK != '' }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          SLACK_MESSAGE: build job for ${{ needs.get-diff.outputs.diff || 'zlib.net' }} ${{ steps.status.outputs.status }}
          SLACK_COLOR: ${{ steps.status.outputs.status }}
